### 회원가입 #사진 없음(사진 있을 경우 file 키 값 추가)
POST http://localhost:9200/auth/signup
Content-Type: application/json

{
  "name": "이름1",
  "email": "name2@duksung.ac.kr",
  "nickname": "닉네임2",
  "password": "1111",
  "phone": "010-1111-2222"
}

### 로그인
POST http://localhost:9200/auth/signin
Content-Type: application/json

{
  "email" : "name2@duksung.ac.kr",
  "password" : "1111"
}

### 로그아웃
GET http://localhost:9200/auth/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0NDkiLCJpYXQiOjE2MzMyNjgzNzEsImV4cCI6MTYzMzM1NDc3MX0.UChlCbStxpqTRpTbdnsW7mcyhPgfmukcUSBGYb3kvam2viHQSeGZYp9KjDUwTCdqiZ8YD3Owqe3cl_fFsWVFkw


### 로그인 안 한 유저가 접근
GET http://localhost:9200/meetings
Content-Type: application/json

### 모두 O
GET http://localhost:9200/member/find/name
Content-Type: application/json

### 로그인만 O
GET http://localhost:9200/member/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2NSIsImlhdCI6MTYzMzk2MDMzMiwiZXhwIjoxNjM0MDQ2NzMyfQ._artTSAqfGIpCkBHl3QNWQU-Djn83mLStRlB9e9uRJIXtBIEsWhCEJD_Sjrp7yfFJta-J4ckojeUj7gZ9a05cQ


###
GET http://localhost:9200/member
Content-Type: application/json