### 회원가입 #사진 없음(사진 있을 경우 file 키 값 추가)
POST http://localhost:9200/api/auth/signup
Content-Type: application/json

{
  "name": "이름1",
  "nickname": "닉네임1",
  "email": "name@duksung.ac.kr",
  "password": "1111",
  "phone": "010-1111-2222",
  "university": "덕성여대"
}

### 로그인
POST http://localhost:9200/auth/signin
Content-Type: application/x-www-form-urlencoded

email=name@duksung.ac.kr&password=1111

### 로그아웃
POST http://localhost:9200/logout
Content-Type: application/json